services:
  - name: euphoria-web
    type: web
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: euphoria-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false

databases:
  - name: euphoria-db
    databaseName: euphoria_dress_production
    user: euphoria
    # Optionally, you can add a password here if your database requires it
    # password: your_database_password
