services:
  - name: euphoria-web
    type: web
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: euphoria-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_USERNAME
        value: euphoria  # Use the database user from your database config
      - key: DATABASE_PASSWORD
        generateValue: true  # Or provide a secure password

databases:
  - name: euphoria-db
    databaseName: euphoria_dress_production
    user: euphoria