default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: euphoria_ecommerce_development
  username: postgres
  password: 123
  host: localhost

test:
  <<: *default
  database: euphoria_ecommerce_test
  username: postgres
  password: 123
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV['DATABASE_NAME'] || 'euphoria_ecommerce_production' %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>